language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.9
install:
  - pip install Django>=$DJANGO_VERSION
  - pip install -e .
script:
  - ./example/manage.py test pages
branches:
  only:
    - master